/*
 * This file is generated by jOOQ.
 */
package com.axopen.frigostrock.model;


import com.axopen.frigostrock.model.tables.Aliment;
import com.axopen.frigostrock.model.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.aliment</code>.
     */
    public static final Aliment ALIMENT = Aliment.ALIMENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
